# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: AUV IITK
completetitle: Autonomous Underwater Vehicle Team, IIT Kanpur
email: iitkauv@gmail.com
description: > # this means to ignore newlines until "url:"
              Official Website for Autonomous Underwater Vehicle (AUV) Team at IIT Kanpur, India
keywords: auv, robotics, iitk, ros, opencv
footer_text: >

url: # the base hostname & protocol for your site
baseurl:   # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# Team Logo
favicon: auvlogo # put name of company icon (.ico)
nav_icon: auv_logo_blue # put name of company icon for navigation bar
logo: auv_logo_white

# google-analytics
google_analytics: UA-111400364-1
repo: http://github.com/AUV-IITK

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: AUV-IITK # put your github username
facebook_username: auviitk # put your facebook username
youtube_username: channel/UCBaRXMUGSoJeHLFBMa0q7Vg # put your youtube username
twitter_username: # put your twitter username
linkedin_username: company/auv-iitk # put your linkedin username
contact_note: #  You can even add a little note about which of these is the best way to reach you.

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: "AUVeScope"
blog_description: "A blog for tutorials, musings, and news"

# Pagination
paginate: 4
permalink: /blog/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_url: auviitk.com
disqus_shortname:  # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  - team
  - subteams
  - vehicles
  - categories

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages', '_categories']

# plugins
plugins:
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
# katex_version: "0.7.1"
anchorjs_version: "3.2.2"
github: [metadata]
